const INITIAL_CITY_BALANCE = 1000000;
const REPRESENTATIVE_PORTION = 1000;
const GRID_SIZE = 10;
const MAX_COUNTRIES_AMOUNT = 20;
const PATH_TO_THE_INPUT_FILE = './input.txt';

module.exports = {
  INITIAL_CITY_BALANCE,
  REPRESENTATIVE_PORTION,
  GRID_SIZE,
  MAX_COUNTRIES_AMOUNT,
  PATH_TO_THE_INPUT_FILE
};
